services:
  nats:
    image: nats:2.10
    command: ["-js", "-m", "8222", "-store_dir", "/data/nats/jetstream"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats_data:/data/nats


  # Python service that continually scrapes metrics and publishes them to NATS
  pub:
    build:
      dockerfile: Dockerfile.pub
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./pub/db/data:/pub/db/data
    command: ["/bin/bash", "entrypoint.sh"]
    depends_on:
      - nats

  sub:
    build:
      dockerfile: Dockerfile.sub
    volumes:
      - ./sub/db/data:/sub/db/data
    command: ["/bin/bash", "entrypoint.sh"]
    depends_on:
      - nats

  sqlite_web:
    image: coleifer/sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./pub/db/data:/data
    command: ["sqlite_web", "/data/devices.db"]
    depends_on:
      - pub
