# --- build  ---
FROM golang:1.23 AS builder

WORKDIR /app

COPY sub/go.mod sub/go.sum ./
RUN go mod download

COPY sub/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o subscriber main.go

# ---- Runtime ----
FROM gcr.io/distroless/base
COPY --from=builder /app/subscriber /subscriber

ENTRYPOINT ["/subscriber"]

