"""create tables

Revision ID: aaf6bbd973c5
Revises: 
Create Date: 2025-07-14 14:01:51.845015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf6bbd973c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('cookie', sa.Text(), nullable=True),
    sa.Column('cookie_expires', sa.BigInteger(), nullable=True),
    sa.Column('auth_flow', sa.String(), nullable=True),
    sa.Column('scraper', sa.String(), nullable=True),
    sa.Column('last_data', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('mac')
    )
    op.create_table('message_info_config',
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('data_field_index', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('machine', sa.String(), nullable=True),
    sa.Column('machine_stage', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('estimated_pieces', sa.Integer(), nullable=True),
    sa.Column('rfid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('mac', 'data_field_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_info_config')
    op.drop_table('devices')
    # ### end Alembic commands ###
